# Generated by Django 5.2.8 on 2025-11-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plato',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
